springdoc:
  api-docs:
    path: "/api-docs"

management:
  endpoints:
    web:
      exposure:
        include:
          - "httptrace"
          - "health"
          - "info"
          - "conditions"
          - "beans"
server:
  port: 30001
